[package]
name = "wasm-bindgen-lifetime-issue"
version = "0.1.0"
authors = ["William Hua <william@attente.ca>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.31"
